openapi: "3.0.0"
info:
  title: GoOutSafe API gateway
  version: "0.0.1"
paths:
  /login:
    post:
      description: Logs in and returns the authentication cookie
      operationId: api_gateway.views.auth.login
      requestBody:
        required: true
        description: Form-data containing email and password
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                  format: password
              required:
                - email
                - password
      responses:
        '200':
          description: Successful login
          headers: 
            Set-Cookie:
              schema: 
                type: string
                example: "gooutsafe_jwt_token=3b1bf43.112322ff34c.4321ef3ba"
        '401':
          description: Authentication failed